/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as LangServicesRouteImport } from './routes/$lang.services'
import { Route as LangPaymentRouteImport } from './routes/$lang.payment'
import { Route as LangGalleryRouteImport } from './routes/$lang.gallery'
import { Route as LangFaqRouteImport } from './routes/$lang.faq'
import { Route as LangCoursesRouteImport } from './routes/$lang.courses'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangAboutRouteImport } from './routes/$lang.about'
import { Route as LangQuizCourseRouteImport } from './routes/$lang.quiz.$course'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/admin/results',
  path: '/admin/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LangServicesRoute = LangServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LangRoute,
} as any)
const LangPaymentRoute = LangPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => LangRoute,
} as any)
const LangGalleryRoute = LangGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => LangRoute,
} as any)
const LangFaqRoute = LangFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LangRoute,
} as any)
const LangCoursesRoute = LangCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangQuizCourseRoute = LangQuizCourseRouteImport.update({
  id: '/quiz/$course',
  path: '/quiz/$course',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/courses': typeof LangCoursesRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/gallery': typeof LangGalleryRoute
  '/$lang/payment': typeof LangPaymentRoute
  '/$lang/services': typeof LangServicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/results': typeof AdminResultsRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/quiz/$course': typeof LangQuizCourseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/courses': typeof LangCoursesRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/gallery': typeof LangGalleryRoute
  '/$lang/payment': typeof LangPaymentRoute
  '/$lang/services': typeof LangServicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/results': typeof AdminResultsRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/quiz/$course': typeof LangQuizCourseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/courses': typeof LangCoursesRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/gallery': typeof LangGalleryRoute
  '/$lang/payment': typeof LangPaymentRoute
  '/$lang/services': typeof LangServicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/results': typeof AdminResultsRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/quiz/$course': typeof LangQuizCourseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/courses'
    | '/$lang/faq'
    | '/$lang/gallery'
    | '/$lang/payment'
    | '/$lang/services'
    | '/admin/login'
    | '/admin/results'
    | '/$lang/'
    | '/$lang/quiz/$course'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/courses'
    | '/$lang/faq'
    | '/$lang/gallery'
    | '/$lang/payment'
    | '/$lang/services'
    | '/admin/login'
    | '/admin/results'
    | '/$lang'
    | '/$lang/quiz/$course'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/courses'
    | '/$lang/faq'
    | '/$lang/gallery'
    | '/$lang/payment'
    | '/$lang/services'
    | '/admin/login'
    | '/admin/results'
    | '/$lang/'
    | '/$lang/quiz/$course'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResultsRoute: typeof AdminResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/admin/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/services': {
      id: '/$lang/services'
      path: '/services'
      fullPath: '/$lang/services'
      preLoaderRoute: typeof LangServicesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/payment': {
      id: '/$lang/payment'
      path: '/payment'
      fullPath: '/$lang/payment'
      preLoaderRoute: typeof LangPaymentRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/gallery': {
      id: '/$lang/gallery'
      path: '/gallery'
      fullPath: '/$lang/gallery'
      preLoaderRoute: typeof LangGalleryRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/faq': {
      id: '/$lang/faq'
      path: '/faq'
      fullPath: '/$lang/faq'
      preLoaderRoute: typeof LangFaqRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/courses': {
      id: '/$lang/courses'
      path: '/courses'
      fullPath: '/$lang/courses'
      preLoaderRoute: typeof LangCoursesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/quiz/$course': {
      id: '/$lang/quiz/$course'
      path: '/quiz/$course'
      fullPath: '/$lang/quiz/$course'
      preLoaderRoute: typeof LangQuizCourseRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangContactRoute: typeof LangContactRoute
  LangCoursesRoute: typeof LangCoursesRoute
  LangFaqRoute: typeof LangFaqRoute
  LangGalleryRoute: typeof LangGalleryRoute
  LangPaymentRoute: typeof LangPaymentRoute
  LangServicesRoute: typeof LangServicesRoute
  LangIndexRoute: typeof LangIndexRoute
  LangQuizCourseRoute: typeof LangQuizCourseRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangContactRoute: LangContactRoute,
  LangCoursesRoute: LangCoursesRoute,
  LangFaqRoute: LangFaqRoute,
  LangGalleryRoute: LangGalleryRoute,
  LangPaymentRoute: LangPaymentRoute,
  LangServicesRoute: LangServicesRoute,
  LangIndexRoute: LangIndexRoute,
  LangQuizCourseRoute: LangQuizCourseRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminResultsRoute: AdminResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
